version: '3.8'

services:

  frontend:
    container_name: frontends
    build:
      context: ./
      dockerfile: Dockerfile
    image: frontend
    ports:
      - 3000:3000
    restart: unless-stopped